const data = [
    {
        id:"1",
        title:"How to learn programming fast",
        author:"Joseph",
        post:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur nam, totam omnis ut nemo sapiente quae eos voluptatem? Perspiciatis saepe minima amet totam perferendis modi mollitia velit debitis minus aspernatur sit deleniti sed sunt eligendi ratione quas, eum reiciendis iusto libero? Molestiae harum a laudantium exercitationem similique. Vitae nobis, sapiente maiores nihil, deserunt nulla laborum adipisci nisi impedit explicabo repellendus id? Tempore cum sint asperiores nobis qui culpa, in sequi quod consectetur dicta mollitia? Aperiam expedita autem quia quod magni eaque repudiandae minima aspernatur illo dolores, illum natus ad. Sapiente asperiores voluptatum, voluptate rem ab alias consequuntur placeat iste voluptatibus Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur nam, totam omnis ut nemo sapiente quae eos voluptatem? Perspiciatis saepe minima amet totam perferendis modi mollitia velit debitis minus aspernatur sit deleniti sed sunt eligendi ratione quas, eum reiciendis iusto libero? Molestiae harum a laudantium exercitationem similique. Vitae nobis, sapiente maiores nihil, deserunt nulla laborum adipisci nisi impedit explicabo repellendus id? Tempore cum sint asperiores nobis qui culpa, in sequi quod consectetur dicta mollitia? Aperiam expedita autem quia quod magni eaque repudiandae minima aspernatur illo dolores, illum natus ad. Sapiente asperiores voluptatum, voluptate rem ab alias consequuntur placeat iste voluptatibus"
    },
    {
        id:"2",
        title:"How to teach kids programming",
        author:"Micheal",
        post: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur nam, totam omnis ut nemo sapiente quae eos voluptatem? Perspiciatis saepe minima amet totam perferendis modi mollitia velit debitis minus aspernatur sit deleniti sed sunt eligendi ratione quas, eum reiciendis iusto libero? Molestiae harum a laudantium exercitationem similique. Vitae nobis, sapiente maiores nihil, deserunt nulla laborum adipisci nisi impedit explicabo repellendus id? Tempore cum sint asperiores nobis qui culpa, in sequi quod consectetur dicta mollitia? Aperiam expedita autem quia quod magni eaque repudiandae minima aspernatur illo dolores, illum natus ad. Sapiente asperiores voluptatum, voluptate rem ab alias consequuntur placeat iste voluptatibus Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur nam, totam omnis ut nemo sapiente quae eos voluptatem? Perspiciatis saepe minima amet totam perferendis modi mollitia velit debitis minus aspernatur sit deleniti sed sunt eligendi ratione quas, eum reiciendis iusto libero? Molestiae harum a laudantium exercitationem similique. Vitae nobis, sapiente maiores nihil, deserunt nulla laborum adipisci nisi impedit explicabo repellendus id? Tempore cum sint asperiores nobis qui culpa, in sequi quod consectetur dicta mollitia? Aperiam expedita autem quia quod magni eaque repudiandae minima aspernatur illo dolores, illum natus ad. Sapiente asperiores voluptatum, voluptate rem ab alias consequuntur placeat iste voluptatibus"
    },
    {
        id:"3",
        title:"Mentor and Leadership in Tech",
        author:"Nancy",
        post: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur nam, totam omnis ut nemo sapiente quae eos voluptatem? Perspiciatis saepe minima amet totam perferendis modi mollitia velit debitis minus aspernatur sit deleniti sed sunt eligendi ratione quas, eum reiciendis iusto libero? Molestiae harum a laudantium exercitationem similique. Vitae nobis, sapiente maiores nihil, deserunt nulla laborum adipisci nisi impedit explicabo repellendus id? Tempore cum sint asperiores nobis qui culpa, in sequi quod consectetur dicta mollitia? Aperiam expedita autem quia quod magni eaque repudiandae minima aspernatur illo dolores, illum natus ad. Sapiente asperiores voluptatum, voluptate rem ab alias consequuntur placeat iste voluptatibus Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur nam, totam omnis ut nemo sapiente quae eos voluptatem? Perspiciatis saepe minima amet totam perferendis modi mollitia velit debitis minus aspernatur sit deleniti sed sunt eligendi ratione quas, eum reiciendis iusto libero? Molestiae harum a laudantium exercitationem similique. Vitae nobis, sapiente maiores nihil, deserunt nulla laborum adipisci nisi impedit explicabo repellendus id? Tempore cum sint asperiores nobis qui culpa, in sequi quod consectetur dicta mollitia? Aperiam expedita autem quia quod magni eaque repudiandae minima aspernatur illo dolores, illum natus ad. Sapiente asperiores voluptatum, voluptate rem ab alias consequuntur placeat iste voluptatibus"
    },
    {
        id:"4",
        title:"Record keeping in Programming career",
        author:"Miracle Joseph",
        post: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur nam, totam omnis ut nemo sapiente quae eos voluptatem? Perspiciatis saepe minima amet totam perferendis modi mollitia velit debitis minus aspernatur sit deleniti sed sunt eligendi ratione quas, eum reiciendis iusto libero? Molestiae harum a laudantium exercitationem similique. Vitae nobis, sapiente maiores nihil, deserunt nulla laborum adipisci nisi impedit explicabo repellendus id? Tempore cum sint asperiores nobis qui culpa, in sequi quod consectetur dicta mollitia? Aperiam expedita autem quia quod magni eaque repudiandae minima aspernatur illo dolores, illum natus ad. Sapiente asperiores voluptatum, voluptate rem ab alias consequuntur placeat iste voluptatibus Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur nam, totam omnis ut nemo sapiente quae eos voluptatem? Perspiciatis saepe minima amet totam perferendis modi mollitia velit debitis minus aspernatur sit deleniti sed sunt eligendi ratione quas, eum reiciendis iusto libero? Molestiae harum a laudantium exercitationem similique. Vitae nobis, sapiente maiores nihil, deserunt nulla laborum adipisci nisi impedit explicabo repellendus id? Tempore cum sint asperiores nobis qui culpa, in sequi quod consectetur dicta mollitia? Aperiam expedita autem quia quod magni eaque repudiandae minima aspernatur illo dolores, illum natus ad. Sapiente asperiores voluptatum, voluptate rem ab alias consequuntur placeat iste voluptatibus"
    },
    {
        id:"5",
        title:" React.js",
        author:"Francis",
        post: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur nam, totam omnis ut nemo sapiente quae eos voluptatem? Perspiciatis saepe minima amet totam perferendis modi mollitia velit debitis minus aspernatur sit deleniti sed sunt eligendi ratione quas, eum reiciendis iusto libero? Molestiae harum a laudantium exercitationem similique. Vitae nobis, sapiente maiores nihil, deserunt nulla laborum adipisci nisi impedit explicabo repellendus id? Tempore cum sint asperiores nobis qui culpa, in sequi quod consectetur dicta mollitia? Aperiam expedita autem quia quod magni eaque repudiandae minima aspernatur illo dolores, illum natus ad. Sapiente asperiores voluptatum, voluptate rem ab alias consequuntur placeat iste voluptatibus Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur nam, totam omnis ut nemo sapiente quae eos voluptatem? Perspiciatis saepe minima amet totam perferendis modi mollitia velit debitis minus aspernatur sit deleniti sed sunt eligendi ratione quas, eum reiciendis iusto libero? Molestiae harum a laudantium exercitationem similique. Vitae nobis, sapiente maiores nihil, deserunt nulla laborum adipisci nisi impedit explicabo repellendus id? Tempore cum sint asperiores nobis qui culpa, in sequi quod consectetur dicta mollitia? Aperiam expedita autem quia quod magni eaque repudiandae minima aspernatur illo dolores, illum natus ad. Sapiente asperiores voluptatum, voluptate rem ab alias consequuntur placeat iste voluptatibus"
    },
    {
        id:"6",
        title:"How to learn coding without sleeping",
        author:"Abraham",
        post: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur nam, totam omnis ut nemo sapiente quae eos voluptatem? Perspiciatis saepe minima amet totam perferendis modi mollitia velit debitis minus aspernatur sit deleniti sed sunt eligendi ratione quas, eum reiciendis iusto libero? Molestiae harum a laudantium exercitationem similique. Vitae nobis, sapiente maiores nihil, deserunt nulla laborum adipisci nisi impedit explicabo repellendus id? Tempore cum sint asperiores nobis qui culpa, in sequi quod consectetur dicta mollitia? Aperiam expedita autem quia quod magni eaque repudiandae minima aspernatur illo dolores, illum natus ad. Sapiente asperiores voluptatum, voluptate rem ab alias consequuntur placeat iste voluptatibus Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur nam, totam omnis ut nemo sapiente quae eos voluptatem? Perspiciatis saepe minima amet totam perferendis modi mollitia velit debitis minus aspernatur sit deleniti sed sunt eligendi ratione quas, eum reiciendis iusto libero? Molestiae harum a laudantium exercitationem similique. Vitae nobis, sapiente maiores nihil, deserunt nulla laborum adipisci nisi impedit explicabo repellendus id? Tempore cum sint asperiores nobis qui culpa, in sequi quod consectetur dicta mollitia? Aperiam expedita autem quia quod magni eaque repudiandae minima aspernatur illo dolores, illum natus ad. Sapiente asperiores voluptatum, voluptate rem ab alias consequuntur placeat iste voluptatibus"
    },
    
]

module.exports = data

